### PR TITLE
Explicitly set the language type for .moc files to enable syntax highlighting

### PR DESCRIPTION
**Pull request by lukeeey**
Screenshot 2023-07-28 at 18 54 12

### CODE REVIEW

**Comment by Sheaffy** [comment]
Sounds like a good idea for code readability. We have a bunch of changes locally to the library that needs to be brought into git, once that is done, I will merge the pull. 

Thanks for the pull request!

**Comment by lukeeey** [comment]
@Sheaffy While you’re here, is it possible to set a background image on a ButtonObject and change the image on mouse down?

**Comment by Sheaffy** [comment]
It is not. You are welcome to give it a try and make a pull request. I am going to be bringing in all our local changes today. Of which is quite substantial since the last update. (for your reference) This version on Github is currently out of date with what you would get by doing a "etallib" update in the system check for update. But that will be changing today.

On second thought there might be a way of doing this however it is not optimal.
You can add a ImageObject as a child of the button with addChildObject()
//ensure the imageObject zDepth is larger than the buttons so it shows on top.
Within the ImageObject onRedraw callback, get the parent object like this
```
onRedraw=function(){
 local parent = this.parentObject;
 //get its button state
 local button_state = parent.buttonState;
 if(button_state == 1) //mouse down
 {
   //we need to load the new image and set the image to use.
   this.imagePath = "newImage.jpg"
   this.nImageID = ICR_LoadImage(this.imagePath);
   local size = ICR_GetImageSize(this.nImageID); 
   this.imageSize = {x = size.WIDTH, y = size.HEIGHT};
 } else {
   //reload the old image
   this.imagePath = "Image.jpg"
   this.nImageID = ICR_LoadImage(this.imagePath);
   local size = ICR_GetImageSize(this.nImageID); 
   this.imageSize = {x = size.WIDTH, y = size.HEIGHT};
 }
}
```
It is worth noting this is not optimal as it will load the image into ram every time a draw event is called as opposed to just once when the Image Object is created. It is also worth noting i have not run this code or tested the theory. The idea is sound and should work.

For future reference I wont be answering questions unrelated to pull requests in pull requests, if you have a question or anything of the like, open a issue :)

**Comment by Sheaffy** [comment]
Thanks again for the PR, all merged in now. I also committed all our local changes, which include a few more objects, like FontAwesome icon object for rendering icons (does not contain FA pro font), and a Tab object for tabbed content. (documentation to follow).

As well as a new set of constraints called RightConstraint and BottomConstraint, RightPercentageConstraint, BottomPercentageConstraint for when you want something to be positioned relative to the bottom or right of another object.

**Pull request merged**
